# Generated by Django 5.1.7 on 2025-05-16 16:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='plan_name',
            field=models.CharField(help_text='Tên kế hoạch tập luyện', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='healthjournal',
            name='note',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
