# Generated by Django 5.1.7 on 2025-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Người dùng'), ('expert', 'Chuyên gia'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
