# Generated by Django 5.1.7 on 2025-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Người dùng'), ('expert', 'Chuyên gia')], default='user', max_length=20),
        ),
    ]
