# Generated by Django 5.1.7 on 2025-05-03 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0002_remove_mealplan_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healths.userprofile'),
        ),
    ]
