# Generated by Django 5.1.7 on 2025-06-02 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='goal',
            field=models.CharField(choices=[('gain_muscle', 'Tăng cơ'), ('lose_weight', 'Giảm cân'), ('maintain', 'Duy trì sức khỏe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mealplanmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healths.meal'),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='connected_nutritionist',
            field=models.ForeignKey(blank=True, limit_choices_to={'expert_type': 'nutritionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutritionist_clients', to='healths.expert'),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='connected_trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'expert_type': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_clients', to='healths.expert'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healths.workout'),
        ),
    ]
