# Generated by Django 5.1.7 on 2025-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0004_alter_healthprofile_goal_alter_healthprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(help_text='Chiều cao (cm)'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(help_text='Cân nặng (kg)'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(help_text='Thời gian (phút)'),
        ),
    ]
