# Generated by Django 5.1.7 on 2025-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0005_alter_healthprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthtracking',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
