# Generated by Django 5.1.7 on 2025-06-04 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0006_alter_healthtracking_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workoutplan',
            name='status',
        ),
        migrations.AddField(
            model_name='meal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='suggested_to',
            field=models.ForeignKey(blank=True, help_text='User cụ thể mà nutritionst gợi ý bài tập này', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_meals', to='healths.regularuser'),
        ),
        migrations.AddField(
            model_name='workout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='suggested_to',
            field=models.ForeignKey(blank=True, help_text='User cụ thể mà trainer gợi ý bài tập này', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_workouts', to='healths.regularuser'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(blank=True, choices=[('gain_muscle', 'Tăng cơ'), ('lose_weight', 'Giảm cân'), ('maintain', 'Duy trì sức khỏe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='plan_name',
            field=models.CharField(default='Kế hoạch mặc định', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Thời gian (phút)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='goal',
            field=models.CharField(blank=True, choices=[('gain_muscle', 'Tăng cơ'), ('lose_weight', 'Giảm cân'), ('maintain', 'Duy trì sức khỏe')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='goal',
            field=models.CharField(blank=True, choices=[('gain_muscle', 'Tăng cơ'), ('lose_weight', 'Giảm cân'), ('maintain', 'Duy trì sức khỏe')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='healths.regularuser'),
        ),
        migrations.AlterField(
            model_name='mealplanmeal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealplanmeal',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealplan_meals', to='healths.mealplan'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='healths.regularuser'),
        ),
    ]
