# Generated by Django 5.1.7 on 2025-06-05 15:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0008_alter_user_role_alter_workoutsession_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=20),
        ),
    ]
