# Generated by Django 5.1.7 on 2025-06-06 07:20
from datetime import time

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0009_chatmessage_image_chatmessage_is_revoked_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='reminder',
        #     name='send_at',
        # ),
        migrations.AddField(
            model_name='reminder',
            name='remind_time',
            field=models.TimeField(default=time(3, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_days',
            field=models.CharField(blank=True, default='', help_text='CSV các ngày lặp lại: mon,tue,wed,...', max_length=50),
        ),
    ]
